### ISSUE TITLE
seeds.rb uses #create instead of #create!

### ISSUE THREAD

**Issue by nachokb** [harrystech/seed_migration#27]
Doc says "At this point, your seeds file will be rewritten with all the create! statements". But I see it's using #create (and thus failing silently).

**Comment by bhavinjavia** [comment]
+1. We are in the process of migrating our seeds to this gem and seeing `create` instead of `create!` in the generated seeds file makes me nervous

**Comment by pjambet** [comment]
Hi,

I'm really sorry I didn't reply earlier.
Indeed the `README` is wrong about `create!`.
I think the best solution would be to add a new config so you can choose if it uses the `!` or not. If any of you wants to take of that, I'd be happy to merge a PR, otherwise I'll try to do that soon.

Thanks again.

**Comment by pjambet** [comment]
Just updated the `README`.

**Comment by pjambet** [comment]
Just merged #36 which adds a new option `use_strict_create`. I'll publish `1.1.0` soon.
