### ISSUE TITLE
Replace seed column values with faker data

### ISSUE THREAD

**Issue by KelseyDH** [harrystech/seed_migration#43]
Great gem!  

I'm wondering: Is there a way for this gem to create a dummy seed file from existing data that _excludes sensitive data_ from certain columns (e.g. email) by replacing their value with something else instead?

E.g. I would love to run this gem with Faker (https://github.com/stympy/faker) on all of the columns so that I could replace sensitive data where they may exist.

I'm envisioning a DSL like so:

```
SeedMigration.register User do
  replace :name => "John Smith", :email => Faker::Internet.email
end
```

This would allow easy creation of a safe dummy seed database from existing production data, and even allow the resulting seed.rb file to be checked into git.

**Comment by pjambet** [comment]
Hi @KelseyDH,

This is an interesting idea. It doesn't really fit our use case, that's why we didn't implement anything like this. I would be happy to include this in the gem if you want to work on it. Feel free to open a PR so we can review and discuss the changes.

Thanks again for your collaboration!

**Comment by pjambet** [comment]
Gonna close this since we're not considering this an issue, but as I said, please open a PR if that's a feature you're interested in.
